services:
  builder:
    image: tc39/tcq-reloaded-builder
    build:
      dockerfile: builder.Dockerfile
    volumes:
      - ./:/opt/build
    entrypoint: ["/usr/bin/npm"]

  dev:
    image: node:10.19-slim
    volumes:
      - ./dist:/dist
      - ./node_modules:/node_modules
    env_file:
      - .env-development
    command: node dist/server/server.js
    ports:
      - 3000:3000

  db:
    image: mongo
    ports:
      - 27017:27017

  prod:
    image: tc39/tcq-reloaded
    build:
      dockerfile: service.Dockerfile
    env_file:
      - .env-production
    ports:
      - 3000:3000
