name: Deploy Staging on AWS

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.stage }}
      url: ${{ inputs.deployUrl }}

  call-deploy-with-aws-copilot:
    uses: ./.github/workflows/deploy-with-aws-copilot.template.yml
    with:
      environment: production
      deployUrl: https://tcq-reloaded.com
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
